import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "./components/Header/Header"
import Footer from "./components/Footer/Footer"

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body
                className={`${inter.variable} ${inter.variable} antialiased dark:bg-primary`}
            >
                <div className='max-w-[1320px] w-full px-5 mx-auto mt-[60px]'>
                    <Header />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    )
}
