import type { Metadata } from 'next'
import { SITE_NAME } from './constants/seo.constants'

export const metadata: Metadata = {
	title: {
		default: SITE_NAME,
		template: `%s | ${SITE_NAME}`,
	},
	description: 'Generated by create next app',
}
